name: "k8s deploy"
description: "deploy to k8s"
inputs: 
  # IMAGE_URL:
  #   required: true
  # PROJECT: 
  #   required: true
  # ENERINAPP: 
  #   required: true
  # ENVIRONMENT: 
  #   required: true   
  # TIER: 
  #   required: true  
  AWS_REGION: 
    required: false
    default: "eu-west-1"      
  AWS_ACCESS_KEY:
    required: true
  AWS_SECRET_KEY: 
    required: true
  # PORT: 
  #   required: false
  #   default: "3000"    
  # PUBLISH_URL: 
  #   required: true
  # KUBE_CONFIG_DATA: 
  #   required: true    
  # NAMESPACE: 
  #   required: true
  K8S_TEMPLATES:
    required: false
    default: ".github/k8s/config .github/k8s/worker .github/k8s/delayedjob .github/k8s/service .github/k8s/ingress"    
runs:
  using: "composite"
  steps:

    - name: Set deployment id
      shell: bash
      run: |
        echo DEPLOYMENT_ID="${PROJECT}-${ENVIRONMENT}-${ENERINAPP}" >> $GITHUB_ENV      

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ inputs.AWS_SECRET_KEY }}
        aws-region: ${{ inputs.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registries: ${{ inputs.DOCKER_REGISTRY_NAME }}

    - name: prep manifests
      shell: bash
      run: |
        for tmpl in ${{ inputs.K8S_TEMPLATES}}; do 
          if [ -f ${tmpl}.tmpl ]; then 
            echo "Processiong ${tmpl}.tmpl"
            cat  ${tmpl}.tmpl | envsubst > ${tmpl}.yaml
            echo "Generated ${tmpl}.yaml:"
            cat ${tmpl}.yaml
          fi 
        done 

    - name: apply config
      uses: enerinvest/actions-kubectl-eks@1.0
      with:
        args: kubectl apply -f .github/k8s/config.yaml


